### ISSUE TITLE
NYU Surface normal dataset

### ISSUE THREAD

**Issue by ChenyangLEI** [ygjwd12345/TransDepth#11]
Thanks for the great work!

I have a question about the surface normal dataset: NYU. I download and unzip following the description but I cannot find the surface normal. Can you help me?

Thanks.
```
mkdir -p pytorch/dataset/nyu_depth_v2
python utils/download_from_gdrive.py 1AysroWpfISmm-yRFGBgFTrLy6FjQwvwP pytorch/dataset/nyu_depth_v2/sync.zip
cd pytorch/dataset/nyu_depth_v2
unzip sync.zip
```

**Comment by ygjwd12345** [comment]
It is for depth.
 If you want to run nyu surface normal, you need to go to surface_normal fold first.
And according to https://github.com/MARSLab-UMN/TiltedImageSurfaceNormal to prepare your dataset.

**Comment by shreyaskamathkm** [comment]
Hi,

I am trying to use the download_from_gdrive.py to download the dataset. But it is unable to download the data. Is the dataset link not working?

Best,
SK

**Comment by ygjwd12345** [comment]
No, I am using download_from_gdrive.py to download nyu depth.

**Comment by shreyaskamathkm** [comment]
Let me check it out and debug. Not really sure why the sync.zip  is 0kb.

**Comment by ygjwd12345** [comment]
I have fixed the bug.
