### ISSUE TITLE
The download link has something wrong!

### ISSUE THREAD

**Issue by huacong** [ygjwd12345/TransDepth#14]
In download_from_gdrive.py file,  the link "https://docs.google.com/uc?export=download1AysroWpfISmm-yRFGBgFTrLy6FjQwvwP" has something wrong. I can't have the access to the website.
![image](https://user-images.githubusercontent.com/88373109/153024319-8649a424-1fc3-4ced-8fbe-8afbfe7b187b.png)
![image](https://user-images.githubusercontent.com/88373109/153024449-56fc0793-c493-4790-af07-3d171b1d9b40.png)
The error code is 400, so maybe the link is wrong.
Thanks for your help!

**Comment by ygjwd12345** [comment]
I think you can just use python file.

**Comment by huacong** [comment]
> I think you can just use python file.

Could you share me a link which I could run the wget command to get the sync.zip.
I have something wrong while running the download_from_gdrive.py.
"OpenSSL.SSL.SysCallError: (10054, 'WSAECONNRESET')"
"ssl.SSLError: ("bad handshake: SysCallError(10054, 'WSAECONNRESET')""
"urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1AysroWpfISmm-yRFGBgFTrLy6FjQwvwP (Caused by SSLError(SSLError("bad handshake: SysCallError(10054, 'WSAECONNRESET')")))"
I couldn't solve it.

**Comment by ygjwd12345** [comment]
Please check readme. it works for me.
