### ISSUE TITLE
About the Image

### ISSUE THREAD

**Issue by huacong** [ygjwd12345/TransDepth#15]
when the argument "baseline = false", the image.shape=[1,224,224].
Why adopting the grey image instead of rgb image?

**Comment by huacong** [comment]
When the argument "baseline = ergb0"(event-frame baseline), you get the events(shape: [6,224,224]) from concatenating the original event(shape:[5,224,224]) and the grey image(shape:[1,224,224]).
I don't know the reason. I think you could give more explanations.
Thanks very much!

**Comment by ygjwd12345** [comment]
sorry, can you make your question clearer? you talk about code or paper?

**Comment by huacong** [comment]
> when the argument "baseline = false", the image.shape=[1,224,224].
> Why adopting the grey image instead of rgb image?

sorry, I am wrong... I am very sorry to bother you.
