### ISSUE TITLE
Training on a new dataset

### ISSUE THREAD

**Issue by mvijay97** [ygjwd12345/TransDepth#18]
Hello, how would one go about training on a dataset that is different from kitti or nyu? Thanks!

**Comment by harryvineeth** [comment]
I have the same requirement to run this model for my dataset

**Comment by ygjwd12345** [comment]
From my experience, you need to change [bts_dataloader.py](https://github.com/ygjwd12345/TransDepth/blob/main/pytorch/bts_dataloader.py).
