### ISSUE TITLE
Why the AGD model does not exist in the optimizer

### ISSUE THREAD

**Issue by 760677482** [ygjwd12345/TransDepth#19]
The Training parameters are only encoder and decoder

**Comment by ygjwd12345** [comment]
sorry for this stupid error. I will modify it immediately.

**Comment by ygjwd12345** [comment]
done

**Comment by 760677482** [comment]
> done

Thanks for your reply

**Comment by 760677482** [comment]
Should the AGD module also need be initialized before training like the decoder？

**Comment by ygjwd12345** [comment]
We don't try this.
