### ISSUE TITLE
Pretrained Encoder link

### ISSUE THREAD

**Issue by BrianPugh** [ygjwd12345/TransDepth#2]
In the README, the pretrained encoder cmd should be:

```
wget https://storage.googleapis.com/vit_models/imagenet21k/R50%2BViT-B_16.npz
```

not the current:

```
wget https://storage.googleapis.com/vit_models/imagenet21k/R50-ViT-B_16.npz
```

**Comment by BrianPugh** [comment]
while we're at it, the `mkdir` command should be:

```
mkdir -p ./model/vit_checkpoint/imagenet21k 
```

**Comment by BrianPugh** [comment]
finally, the last command should be:

```
mv R50+ViT-B_16.npz model/vit_checkpoint/imagenet21k/
```
confirmed by the config [you are using here](https://github.com/ygjwd12345/TransDepth/blob/4b5c66710bb85a51105780c0b42544bc200708ab/pytorch/TransUNet/networks/vit_seg_configs.py#L51)

**Comment by BrianPugh** [comment]
and the prepare nyu commands can be shorted to:
```
mkdir -p pytorch/dataset/nyu_depth_v2
python utils/download_from_gdrive.py 1AysroWpfISmm-yRFGBgFTrLy6FjQwvwP pytorch/dataset/nyu_depth_v2/sync.zip
cd pytorch/dataset/nyu_depth_v2
unzip sync.zip
```

**Comment by ygjwd12345** [comment]
> In the README, the pretrained encoder cmd should be:
> 
> ```
> wget https://storage.googleapis.com/vit_models/imagenet21k/R50%2BViT-B_16.npz
> ```
> 
> not the current:
> 
> ```
> wget https://storage.googleapis.com/vit_models/imagenet21k/R50-ViT-B_16.npz
> ```

it is according to ViT
# imagenet21k pre-train
wget https://storage.googleapis.com/vit_models/imagenet21k/{MODEL_NAME}.npz

**Comment by ygjwd12345** [comment]
> and the prepare nyu commands can be shorted to:
> 
> ```
> mkdir -p pytorch/dataset/nyu_depth_v2
> python utils/download_from_gdrive.py 1AysroWpfISmm-yRFGBgFTrLy6FjQwvwP pytorch/dataset/nyu_depth_v2/sync.zip
> cd pytorch/dataset/nyu_depth_v2
> unzip sync.zip
> ```

Thanks

**Comment by BrianPugh** [comment]
the MODEL_NAME has a `+`, not a `-` after `R50`

**Comment by ygjwd12345** [comment]
Sorry it's my mistake

**Comment by ygjwd12345** [comment]
> the MODEL_NAME has a `+`, not a `-` after `R50`

It has be fixed.
