### ISSUE TITLE
How do I train the model on a windows machine?

### ISSUE THREAD

**Issue by ninja-shreyash** [ygjwd12345/TransDepth#20]
I already solved several errors arising due to the code not being directly compatible with windows, but then in the train command, I am getting an error which I can't seem to fix. Can you help me out in this? 
![image](https://user-images.githubusercontent.com/56553419/183245241-3b0e4a0b-8d7a-41fc-a342-1ad7743a52cc.png)

I am using Torch version: 1.8.0 and CUDA: 11.4

**Comment by ygjwd12345** [comment]
Sorry about the delay reply.
I don't have any experience with running at Windocs.
