### ISSUE TITLE
Why design latent kernel structure

### ISSUE THREAD

**Issue by mzy97** [ygjwd12345/TransDepth#6]
Thank you for sharing this wonderful work.
In my opinion, the AGD module is used to select low-level features in the encoder to enhance the feature (encoder output), perform spatial and channel attention will be enough. Why design latent kernel mechanism, what is the motivation and actual improvement using latent kernel?

**Comment by ygjwd12345** [comment]
Projecting a feature to latent space is often better than using the feature directly in practice. It is not our novelty, and we don't talk about it a lot.
